### ISSUE TITLE
Add  Password Validation on the Login Form 

### ISSUE THREAD

**Issue by Pjha72** [Pjha72/Student-Result-Management-System#2]

**Comment by Sky-De** [comment]
hi there 
what kind of validation do you mean? some specific pattern of passwords ?
if you explain 
i can fix this

**Comment by Pjha72** [comment]
Yes min length 6 and one uppercase letter and @ and one numeric value

**Comment by Sky-De** [comment]
sure 
assign it to me 
i will take care about it as soon as it's possible

**Comment by Sky-De** [comment]
Please close this issue 
Cuz i fixed it 
And it's done now
Thanks
